=== raml-apis/PagerDuty/schemas/alerts.json
{
	"type" : "object" ,
	"required" : true ,
	"$schema" : "http://json-schema.org/draft-03/schema" ,
	"properties" : {
		"alerts" : {
			"type" : "array" ,
			"required" : false ,
			"items" : 
				{
					"type" : "object" ,
					"properties" : {
						"id" : {
							"type" : "string" ,
							"required" : false
						} ,
						"type" : {
							"type" : "string" ,
							"required" : false
						} ,
						"started_at" : {
							"type" : "string" ,
							"required" : false
						} ,
						"user" : {
							"type" : "object" ,
							"required" : false
						} ,
						"address" : {
							"type" : "string" ,
							"required" : false
						}
					}
				}
			
		} ,
		"limit" : {
			"type" : "number" ,
			"required" : false
		} ,
		"offset" : {
			"type" : "number" ,
			"required" : false
		} ,
		"total" : {
			"type" : "number" ,
			"required" : false
		}
	}
}

=== raml-apis/PagerDuty/examples/alerts.json
{
	"alerts" : [ {
		"id" : "PWL7QXS" ,
		"type" : "Phone" ,
		"started_at" : "2013-03-06T15:28:50-05:00" ,
		"user" : {
			"id" : "PT23IWX" ,
			"name" : "Tim Wright" ,
			"email" : "tim@acme.com" ,
			"time_zone" : "Eastern Time (US & Canada)" ,
			"color" : "purple" ,
			"role" : "owner" ,
			"avatar_url" :
			"https://secure.gravatar.com/avatar/923a2b907dc04244e9bb5576a42e70a7.png?d=mm&r=PG"
			,
			"user_url" : "/users/PT23IWX" ,
			"invitation_sent" : false ,
			"marketing_opt_out" : false
		} ,
		"address" : "+15555551234"
	} , {
		"id" : "PKN7NBH" ,
		"type" : "Email" ,
		"started_at" : "2013-03-06T15:28:51-05:00" ,
		"user" : {
			"id" : "PT23IWX" ,
			"name" : "Tim Wright" ,
			"email" : "tim@acme.com" ,
			"time_zone" : "Eastern Time (US & Canada)" ,
			"color" : "purple" ,
			"role" : "owner" ,
			"avatar_url" :
			"https://secure.gravatar.com/avatar/923a2b907dc04244e9bb5576a42e70a7.png?d=mm&r=PG"
			,
			"user_url" : "/users/PT23IWX" ,
			"invitation_sent" : false ,
			"marketing_opt_out" : false
		} ,
		"address" : "tim@pagerduty.com"
	} ] ,
	"limit" : 100 ,
	"offset" : 0 ,
	"total" : 2
}
