=== raml-apis/PagerDuty/schemas/integrationRequest-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "service_key" : {
      "type" : "string" ,
      "required" : true
    } ,
    "incident_key" : {
      "type" : "string" ,
      "required" : false
    } ,
    "event_type" : {
      "type" : "string" ,
      "required" : true
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "client" : {
      "type" : "string" ,
      "required" : false
    } ,
    "client_url" : {
      "type" : "string" ,
      "required" : false
    } ,
    "details" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
      }
    }
  }
}

=== raml-apis/PagerDuty/examples/integrationRequest-example.json
{
  "service_key" : "e93facc04764012d7bfb002500d5d1a6" ,
  "incident_key" : "srv01/HTTP" ,
  "event_type" : "trigger" ,
  "description" : "FAILURE for production/HTTP on machine srv01.acme.com" ,
  "client" : "Sample Monitoring Service" ,
  "client_url" : "https://monitoring.service.com" ,
  "details" : {
    "ping time" : "1500ms" ,
    "load avg" : 0.75
  }
}
