=== raml-apis/PagerDuty/schemas/maintenanceWindowsQuery.json
{
	"type" : "object" ,
	"required" : true ,
	"$schema" : "http://json-schema.org/draft-03/schema" ,
	"properties" : {
		"maintenance_windows" : {
			"type" : "array" ,
			"required" : false ,
			"items" : 
				{
					"type" : "object" ,
					"properties" : {
						"id" : {
							"type" : "string" ,
							"required" : false
						} ,
						"sequence_number" : {
							"type" : "number" ,
							"required" : false
						} ,
						"start_time" : {
							"type" : "string" ,
							"required" : false
						} ,
						"end_time" : {
							"type" : "string" ,
							"required" : false
						} ,
						"description" : {
							"type" : "string" ,
							"required" : false
						} ,
						"created_by" : {
							"type" : "object" ,
							"required" : false
						} ,
						"services" : {
							"type" : "array" ,
							"required" : false ,
							"items" : 
								{
									"type" : "object" ,
									"properties" : {
										"name" : {
											"type" : "string" ,
											"required" : false
										} ,
										"url" : {
											"type" : "string" ,
											"required" : false
										} ,
										"id" : {
											"type" : "string" ,
											"required" : false
										}
									}
								}
							
						}
					}
				}
			
		} ,
		"limit" : {
			"type" : "number" ,
			"required" : false
		} ,
		"offset" : {
			"type" : "number" ,
			"required" : false
		} ,
		"total" : {
			"type" : "number" ,
			"required" : false
		} ,
		"query" : {
			"type" : "string" ,
			"required" : false
		} ,
		"counts" : {
			"type" : "object" ,
			"required" : false
		}
	}
}

=== raml-apis/PagerDuty/examples/maintenanceWindowsQuery.json
{
	"maintenance_windows" : [ {
		"id" : "P9UJCMM" ,
		"sequence_number" : 1 ,
		"start_time" : "2012-06-16T13:00:00-04:00Z" ,
		"end_time" : "2012-06-16T14:00:00-04:00Z" ,
		"description" :
		"This service is in maintenance due to a scheduled ruby 1.9 migration" ,
		"created_by" : {
			"id" : "PP1565R" ,
			"name" : "John Smith" ,
			"email" : "john@example.com" ,
			"time_zone" : "Eastern Time (US & Canada)" ,
			"color" : "grey20" ,
			"role" : "user" ,
			"avatar_url" :
			"https://secure.gravatar.com/avatar/2e32280905f296791ed387cd0f61ec6b.png?d=mm&r=PG"
			,
			"user_url" : "/users/PP1565R" ,
			"invitation_sent" : true
		} ,
		"services" : [ {
			"name" : "Mail Service 12345677" ,
			"url" : "/services/PF9KMXH" ,
			"id" : "PF9KMXH"
		} ]
	} ] ,
	"limit" : 25 ,
	"offset" : 0 ,
	"total" : 1 ,
	"query" : "ruby 1.9 migration" ,
	"counts" : {
		"ongoing" : 4 ,
		"future" : 3 ,
		"past" : 3 ,
		"all" : 10
	}
}
