=== raml-apis/PagerDuty/schemas/reportsIncidentsPerTime.json
{
	"type" : "object" ,
	"required" : true ,
	"$schema" : "http://json-schema.org/draft-03/schema" ,
	"properties" : {
		"alerts" : {
			"type" : "array" ,
			"required" : false ,
			"items" : 
				{
					"type" : "object" ,
					"properties" : {
						"number_of_alerts" : {
							"type" : "number" ,
							"required" : false
						} ,
						"number_of_phone_alerts" : {
							"type" : "number" ,
							"required" : false
						} ,
						"number_of_sms_alerts" : {
							"type" : "number" ,
							"required" : false
						} ,
						"number_of_email_alerts" : {
							"type" : "number" ,
							"required" : false
						} ,
						"start" : {
							"type" : "string" ,
							"required" : false
						} ,
						"end" : {
							"type" : "string" ,
							"required" : false
						}
					}
				}
			
		} ,
		"total_number_of_alerts" : {
			"type" : "number" ,
			"required" : false
		} ,
		"total_number_of_phone_alerts" : {
			"type" : "number" ,
			"required" : false
		} ,
		"total_number_of_sms_alerts" : {
			"type" : "number" ,
			"required" : false
		} ,
		"total_number_of_email_alerts" : {
			"type" : "number" ,
			"required" : false
		} ,
		"total_number_of_billable_alerts" : {
			"type" : "number" ,
			"required" : false
		}
	}
}

=== raml-apis/PagerDuty/examples/reportsIncidentsPerTime.json
{
	"alerts" : [ {
		"number_of_alerts" : 17 ,
		"number_of_phone_alerts" : 11 ,
		"number_of_sms_alerts" : 2 ,
		"number_of_email_alerts" : 4 ,
		"start" : "2012-06-01T07:00:00Z" ,
		"end" : "2012-07-01T00:00:00-07:00"
	} , {
		"number_of_alerts" : 22 ,
		"number_of_phone_alerts" : 12 ,
		"number_of_sms_alerts" : 5 ,
		"number_of_email_alerts" : 5 ,
		"start" : "2012-07-01T07:00:00Z" ,
		"end" : "2012-08-01T00:00:00-07:00"
	} ] ,
	"total_number_of_alerts" : 39 ,
	"total_number_of_phone_alerts" : 23 ,
	"total_number_of_sms_alerts" : 7 ,
	"total_number_of_email_alerts" : 9 ,
	"total_number_of_billable_alerts" : 30
}
