=== raml-apis/PagerDuty/schemas/usersQuery.json
{
	"type" : "object" ,
	"required" : true ,
	"$schema" : "http://json-schema.org/draft-03/schema" ,
	"properties" : {
		"users" : {
			"type" : "array" ,
			"required" : false ,
			"items" : 
				{
					"type" : "object" ,
					"properties" : {
						"id" : {
							"type" : "string" ,
							"required" : false
						} ,
						"name" : {
							"type" : "string" ,
							"required" : false
						} ,
						"email" : {
							"type" : "string" ,
							"required" : false
						} ,
						"time_zone" : {
							"type" : "string" ,
							"required" : false
						} ,
						"color" : {
							"type" : "string" ,
							"required" : false
						} ,
						"role" : {
							"type" : "string" ,
							"required" : false
						} ,
						"avatar_url" : {
							"type" : "string" ,
							"required" : false
						} ,
						"user_url" : {
							"type" : "string" ,
							"required" : false
						} ,
						"invitation_sent" : {
							"type" : "boolean" ,
							"required" : false
						}
					}
				}
			
		} ,
		"active_account_users" : {
			"type" : "number" ,
			"required" : false
		} ,
		"limit" : {
			"type" : "number" ,
			"required" : false
		} ,
		"query" : {
			"type" : "string" ,
			"required" : false
		} ,
		"offset" : {
			"type" : "number" ,
			"required" : false
		} ,
		"total" : {
			"type" : "number" ,
			"required" : false
		}
	}
}

=== raml-apis/PagerDuty/examples/usersQuery.json
{
	"users" : [ {
		"id" : "PP1565R" ,
		"name" : "John Smith" ,
		"email" : "john@example.com" ,
		"time_zone" : "Eastern Time (US & Canada)" ,
		"color" : "grey20" ,
		"role" : "user" ,
		"avatar_url" :
		"https://secure.gravatar.com/avatar/2e32280905f296791ed387cd0f61ec6b.png?d=mm&r=PG"
		,
		"user_url" : "/users/PP1565R" ,
		"invitation_sent" : true
	} ] ,
	"active_account_users" : 1 ,
	"limit" : 25 ,
	"query" : "john" ,
	"offset" : 0 ,
	"total" : 1
}
